Article.create(title: "How The West Was Won", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Article.create(title: "Theory of Relativity", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Article.create(title: "Advances in Camera Science", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Article.create(title: "How To Get The Perfect Shot", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget varius tortor. Suspendisse nec sagittis urna. Proin quis convallis dolor. Ut quis eros libero. Cras id laoreet nunc. Nam placerat est in pretium feugiat. Integer accumsan, turpis sit amet tempor efficitur, mi libero feugiat libero, tristique aliquet turpis erat vitae urna. Aenean id velit orci. Maecenas luctus consequat tellus tincidunt congue.

Integer semper orci dictum, vehicula urna nec, imperdiet felis. Sed faucibus ornare tempor. Praesent quis massa at leo fringilla finibus. Phasellus arcu felis, sollicitudin non dui nec, tristique efficitur diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam at mi sodales, elementum lectus eu, vehicula est. Nunc leo nunc, ultricies sed diam sed, imperdiet dapibus libero. Proin fermentum velit non metus imperdiet porttitor. Vestibulum sed egestas mi, at sollicitudin eros. In hac habitasse platea dictumst. Suspendisse auctor, urna non interdum iaculis, leo tortor dapibus ligula, sit amet vehicula ante sapien rutrum augue. Sed eu luctus turpis. Pellentesque molestie varius lectus, quis ultrices justo. Aliquam porttitor quis elit ac bibendum. Duis et lorem et massa posuere blandit ut nec est. Duis suscipit suscipit massa, et convallis odio vulputate at.

Curabitur ornare commodo sem, et volutpat ex dapibus quis. Morbi hendrerit dolor at eros tristique ultrices. Aenean vehicula vulputate nulla, facilisis porttitor justo tempor et. Pellentesque eget velit laoreet, bibendum lectus vel, tristique justo. Ut sit amet fringilla lectus. Donec convallis risus eros, nec volutpat tortor scelerisque a. Duis sed sapien imperdiet, feugiat tortor quis, egestas quam. Quisque tempor, risus ut vestibulum condimentum, justo metus fringilla nibh, in rhoncus eros ipsum ut est. In sed condimentum ligula. Nullam dictum tortor non posuere aliquet. Pellentesque a ante nec nibh volutpat iaculis quis in lacus.

Cras vehicula, lacus id vulputate hendrerit, enim odio aliquam arcu, sit amet tempor nibh sapien et urna. Etiam dictum quam varius nunc scelerisque tristique. Morbi euismod, purus in facilisis tempus, lorem est tincidunt sem, eu tincidunt elit eros vitae neque. Suspendisse in lacus diam. Curabitur varius mi quis sapien elementum vehicula. Quisque nibh justo, porttitor a aliquam et, pretium sit amet diam. Donec ac lectus aliquet, dapibus purus vel, hendrerit risus. Donec tincidunt luctus mi et interdum. Ut hendrerit dui et ultricies imperdiet. Suspendisse nulla justo, mattis sit amet mollis laoreet, volutpat id enim. Cras eget aliquam eros. Aliquam mattis lobortis nisl feugiat vehicula. Nulla eget nulla id justo imperdiet imperdiet eget at urna. Integer nec ex iaculis, aliquam sapien vel, dictum enim. Aliquam erat volutpat.

Phasellus non arcu eget massa sollicitudin facilisis et id nulla. Curabitur scelerisque venenatis interdum. Nunc dictum posuere turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent posuere egestas orci, ut suscipit sapien egestas a. Curabitur vitae feugiat est. Sed mattis dolor orci, sed egestas quam placerat ac. Morbi interdum sit amet libero vel consequat. Sed nec nulla ut nisl rutrum laoreet.")
Article.create(title: "The Great Journey", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Magna etiam tempor orci eu lobortis elementum nibh. Purus non enim praesent elementum facilisis leo vel fringilla est. Suscipit tellus mauris a diam maecenas sed enim ut. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus et. Tristique senectus et netus et malesuada fames ac. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Nunc sed blandit libero volutpat. At tempor commodo ullamcorper a lacus. A erat nam at lectus.

Cursus turpis massa tincidunt dui ut ornare lectus sit. Donec enim diam vulputate ut. Vel pretium lectus quam id leo. Dolor sit amet consectetur adipiscing elit ut aliquam purus. Nulla at volutpat diam ut venenatis. Ornare arcu odio ut sem nulla pharetra diam. Erat nam at lectus urna duis convallis convallis tellus. Risus in hendrerit gravida rutrum quisque non. Lectus mauris ultrices eros in cursus turpis. Odio pellentesque diam volutpat commodo sed egestas egestas. Leo vel fringilla est ullamcorper. Ipsum consequat nisl vel pretium lectus. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Cras fermentum odio eu feugiat pretium. A iaculis at erat pellentesque adipiscing commodo elit at.

Ipsum dolor sit amet consectetur. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Rhoncus dolor purus non enim praesent elementum. Tincidunt arcu non sodales neque sodales ut etiam sit. Dolor sit amet consectetur adipiscing elit. Tempus iaculis urna id volutpat. Amet mattis vulputate enim nulla aliquet porttitor lacus. Vel quam elementum pulvinar etiam. In mollis nunc sed id semper risus. Odio eu feugiat pretium nibh ipsum consequat. Commodo quis imperdiet massa tincidunt nunc pulvinar. Id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum posuere. Accumsan in nisl nisi scelerisque eu ultrices.

Amet nisl purus in mollis nunc sed id semper risus. At risus viverra adipiscing at. Justo donec enim diam vulputate. Quis commodo odio aenean sed adipiscing diam. Vulputate odio ut enim blandit volutpat maecenas. Imperdiet nulla malesuada pellentesque elit eget gravida. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Sed tempus urna et pharetra pharetra massa massa ultricies. Justo laoreet sit amet cursus sit. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Enim praesent elementum facilisis leo vel. Dignissim convallis aenean et tortor at risus. Quam id leo in vitae turpis massa sed elementum. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Amet est placerat in egestas erat imperdiet sed euismod. Bibendum enim facilisis gravida neque convallis a. Faucibus in ornare quam viverra.

Diam donec adipiscing tristique risus nec feugiat in fermentum. Ac auctor augue mauris augue neque gravida. Lorem sed risus ultricies tristique nulla aliquet enim. A iaculis at erat pellentesque adipiscing commodo elit at. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Eu mi bibendum neque egestas congue quisque egestas diam. Urna et pharetra pharetra massa massa ultricies mi quis. Risus quis varius quam quisque id diam. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Urna molestie at elementum eu facilisis sed. Nullam eget felis eget nunc. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Sed ullamcorper morbi tincidunt ornare massa. Nunc non blandit massa enim nec dui nunc. Lectus sit amet est placerat in. Platea dictumst vestibulum rhoncus est pellentesque. Consectetur lorem donec massa sapien. Aliquam faucibus purus in massa tempor nec feugiat nisl. Porttitor rhoncus dolor purus non enim praesent elementum. Urna duis convallis convallis tellus id interdum velit.")
Article.create(title: "The Influence of Media", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a dui turpis. Fusce interdum leo in nisl eleifend varius. Duis mattis risus quis molestie viverra. Sed eget erat ornare neque posuere malesuada ac a quam. Pellentesque lorem neque, elementum a mi ut, ullamcorper pellentesque turpis. Sed hendrerit suscipit arcu. Nullam viverra venenatis felis, consectetur pellentesque justo rhoncus vel. Ut fermentum nibh nec sem efficitur aliquet. Nam placerat neque mauris, et congue mauris dictum rutrum. Sed massa diam, fringilla id tempus ac, consequat ut tellus. Nunc vitae dui pellentesque nibh convallis hendrerit. Vivamus tempus efficitur sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Suspendisse at fermentum elit. Vestibulum nibh purus, luctus in odio et, tempor lacinia ante. Sed ornare justo ac maximus maximus. Mauris in metus eu ipsum aliquam hendrerit a a ligula. Fusce vel sollicitudin ligula, id feugiat dolor. In hac habitasse platea dictumst. Aliquam sit amet orci quam. Cras bibendum ipsum id blandit posuere. Ut in dolor in leo malesuada gravida et non sem. Proin vel magna dapibus, malesuada tellus consequat, vestibulum augue. Vestibulum eu arcu nec leo placerat rutrum. Mauris venenatis nisl quis ornare volutpat.

Morbi lobortis condimentum risus. Duis sodales urna ut ligula auctor rhoncus. Curabitur ac dictum lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultricies pharetra lectus ut molestie. Donec euismod est et hendrerit dignissim. Sed cursus, orci eget varius accumsan, orci est tincidunt sem, ut aliquam massa velit sit amet turpis. Curabitur posuere, justo vitae pulvinar egestas, arcu tellus hendrerit nisi, at elementum nulla nisi eget quam. Nam fringilla eget ligula eget eleifend. Sed tincidunt elit in erat luctus ornare. Proin luctus eget leo venenatis interdum.

Quisque finibus nisi sapien, vitae lobortis nisl imperdiet sed. Nulla a arcu mattis, porttitor diam ut, consectetur felis. Fusce libero ante, elementum at nunc ac, condimentum dapibus tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dolor nunc, volutpat in mi eget, aliquet rhoncus orci. Nulla ex diam, interdum eu magna quis, viverra elementum neque. Pellentesque tincidunt a dui id pellentesque. In consequat elit ut ipsum malesuada molestie. Sed malesuada porttitor quam in luctus. Aenean pharetra et tortor quis sollicitudin. Donec nec odio eu velit suscipit euismod. Nullam accumsan ligula nunc, a varius neque rhoncus vitae. Mauris at venenatis orci.

Sed vel iaculis lorem, blandit laoreet tellus. Donec sagittis auctor congue. Mauris varius ut tortor sed ullamcorper. Vestibulum posuere sed dolor vel egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eget ipsum mauris. Donec pellentesque suscipit lorem, sit amet facilisis felis tempor et. Praesent id neque at nisl rhoncus iaculis a non ex. Praesent varius lorem quis lacus ornare fringilla. Aenean mollis lacinia est, vitae commodo nisl suscipit quis.")
